spring.application.name=demo1dashboard
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USERNAME:myUser}
spring.datasource.password=${DB_PASSWORD:myPass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=dashboard
#app.admin.username=admin
#app.admin.password=Admin@123